enum GrowActionType {
  WATER = 'WATER',
  TRIM = 'TRIM',
  FEED = 'FEED',
  HARVEST = 'HARVEST',
  TRAINING = 'TRAINING',
  OTHER = 'OTHER',
  VPD = 'VPD',
  TEMPERATURE = 'TEMPERATURE',
  LIGHT_INTENSITY = 'LIGHT_INTENSITY',
  HUMIDITY = 'HUMIDITY',
}

export default GrowActionType;
